Update README.md
PTCInc/Kepware-Example-Scripts pull request #8
Opened 2020-09-11 18:00 UTC by MRoyPTC

Changed first line in README to be the inverse of the Export script.

2020-09-14 15:04 UTC, rlabbeptc requested changes

2020-09-14 15:04 UTC, rlabbeptc commented on Datalogger/CSV to DataLogger API/README.md
```suggestion

This script takes CSV log items from Kepware V6.6 and older and allows you to import it into a newer version of Kepware with the the Configuration API available for the Datalogger Plug-in
```

2020-09-14 15:04 UTC, rlabbeptc commented on Datalogger/CSV to DataLogger API/README.md
Just adding some context to the solution

2020-09-15 15:29 UTC, MRoyPTC commented on Datalogger/CSV to DataLogger API/README.md
Based on our conversations, let's remove the references to KSE 6.6 and older.

2020-09-15 15:35 UTC, rlabbeptc approved these changes

2020-09-15 15:37 UTC, merged